### ISSUE TITLE
脚步可以登录知乎么？

### ISSUE THREAD

**Issue by xiaoyuxiaoyu** [SanmuWangZJU/zhihu_spider#1]
我执行脚步会弹出那个验证码的图片，接下来的流程是什么样的呢？我使用这个脚步无法登陆成功

**Comment by SanmuWangZJU** [comment]
点击图片里倒立的文字，然后点击鼠标中建，表示点击动作完成，然后进行下一步。
具体解释看[ Python 脚本登录知乎](http://blog.csdn.net/sinat_37202005/article/details/54406105)
发现现在知乎登录的post信息有所改动，程序中postdata中的内容也要相应修改

**Comment by xiaoyuxiaoyu** [comment]
点击图片倒立的文字，然后点击鼠标右键，还是没有什么响应，打开倒立的文字的时候会出现下面的warnings：D:\Python\lib\site-packages\matplotlib\backend_bases.py:2453: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)

然后当我关掉图片的时候会出现很多错误：
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\matplotlib\blocking_input.py", line 117, in __call__
    self.fig.canvas.start_event_loop(timeout=timeout)
  File "D:\Python\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 514, in start_event_loop
    FigureCanvasBase.start_event_loop_default(self,timeout)
  File "D:\Python\lib\site-packages\matplotlib\backend_bases.py", line 2461, in start_event_loop_default
    self.flush_events()
  File "D:\Python\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 511, in flush_events
    self._master.update()
  File "D:\Python\lib\tkinter\__init__.py", line 1025, in update
    self.tk.call('update')
_tkinter.TclError: can't invoke "update" command: application has been destroyed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\lib\site-packages\matplotlib\backends\tkagg.py", line 22, in blit
    id(data), colormode, id(bbox_array))
_tkinter.TclError: this isn't a Tk application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/PythonRoot/test/my_zhihu.py", line 69, in <module>
    captcha, captcha_type = getcaptcha()
  File "D:/PythonRoot/test/my_zhihu.py", line 61, in getcaptcha
    input_points = getcaptcha_cn()
  File "D:/PythonRoot/test/my_zhihu.py", line 38, in getcaptcha_cn
    pos = plt.ginput(0, 0)
  File "D:\Python\lib\site-packages\matplotlib\pyplot.py", line 712, in ginput
    return gcf().ginput(*args, **kwargs)
  File "D:\Python\lib\site-packages\matplotlib\figure.py", line 1670, in ginput
    show_clicks=show_clicks)
  File "D:\Python\lib\site-packages\matplotlib\blocking_input.py", line 294, in __call__
    BlockingInput.__call__(self, n=n, timeout=timeout)
  File "D:\Python\lib\site-packages\matplotlib\blocking_input.py", line 120, in __call__
    self.cleanup()
  File "D:\Python\lib\site-packages\matplotlib\blocking_input.py", line 281, in cleanup
    self.fig.canvas.draw()
  File "D:\Python\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 352, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "D:\Python\lib\site-packages\matplotlib\backends\tkagg.py", line 30, in blit
    id(data), colormode, id(bbox_array))
_tkinter.TclError: this isn't a Tk application

不知道是不是缺失了什么环境？

**Comment by SanmuWangZJU** [comment]
应该不是缺失环境，BlockingInput.__ call __ ()方法里设置了timeout，不知道是不是超时了？以及试试点击中键后不关这个图片，继续debug程序，看能不能继续跑下去。
现在知乎登录的post信息里的_xsrf好像不能直接从爬下来的网页直接获取了，要通过其它函数计算，你可以看一下post的xsrf的长度和爬下来的xsrf长度是不一致的。具体怎么计算还要继续看它的js代码，你如果感兴趣可以继续做下去。

**Comment by xiaoyuxiaoyu** [comment]
非常感谢帮我解惑，这两天遇到另外一个问题，不知道您有没有研究过？比如我使用了网上的免费代理去访问服务端，最终结果是可以访问的。但是服务端仍然能获取到我本地的IP，不知道有什么办法能隐匿我本地的IP，不是指通过设置header头中的：CLIENT-IP和X-FORWARDED-FOR

**Comment by SanmuWangZJU** [comment]
这个问题我没有做过，抱歉了，或者你挂个VPN再试试？
